version: "3.8"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - FRONTEND_URI=${FRONTEND_URI}
      - MONGO_DB_URI=${MONGO_DB_URI}
    volumes:
      - ./backend/.env:/app/.env 
    depends_on:
      - mongo
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=http://localhost:8080/api
    networks:
      - app-network

  mongo:
    image: mongo:5.0
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - app-network
    command: "--bind_ip_all --quiet"

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
